# Generated by Django 2.1.1 on 2018-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('tipo', models.CharField(blank=True, choices=[('P', 'Producto'), ('S', 'Servicio')], max_length=1, null=True, verbose_name='Tipo')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría del Producto')),
                ('costo', models.FloatField(verbose_name='Costo')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('notas', models.TextField(verbose_name='Notas')),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True, verbose_name='Estado')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualiza', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Gestión de Producto',
                'verbose_name_plural': 'Gestión de Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
