# Generated by Django 2.1.1 on 2018-09-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('tipo_dcto', models.CharField(max_length=15, verbose_name='Identificación')),
                ('correo_e', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('tel_fijo', models.CharField(max_length=15, verbose_name='Fijo')),
                ('tel_movil', models.CharField(max_length=15, verbose_name='Movil')),
                ('direccion1', models.CharField(max_length=40, verbose_name='Dirección')),
                ('direccion2', models.CharField(max_length=40, verbose_name='Dirección 2')),
                ('ciudad', models.CharField(max_length=40, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=40, verbose_name='Departamento')),
                ('pais', models.CharField(max_length=40, verbose_name='País')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualiza', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_crea'],
            },
        ),
    ]
