# Generated by Django 2.1.1 on 2018-09-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20180929_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['-fecha_crea'], 'verbose_name': 'Gestión de Cliente', 'verbose_name_plural': 'Gestión de Clientes'},
        ),
    ]
