# Generated by Django 2.1.1 on 2018-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20180929_0745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['nombre_completo'], 'verbose_name': 'Gestión de Cliente', 'verbose_name_plural': 'Gestión de Clientes'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True, verbose_name='Estado'),
        ),
    ]
